### ISSUE TITLE
Bug: build error 

### ISSUE THREAD

**Issue by crispinknox** [azerothcore/mod-ah-bot#127]
### Current Behaviour

Visual Studio Build Error
'GetAuctionHouseEntryFromFactionTemplate': is not a member of 'AuctionHouseMgr'
'AuctionHouseId': identifier not found
'AuctionHouseId': identifier not found
'AuctionHouseId': is not a class or namespace name
'Alliance': undeclared identifier
'AuctionHouseId': identifier not found
'AuctionHouseId': is not a class or namespace name
'Horde': undeclared identifier
'AuctionHouseId': identifier not found
'AuctionHouseId': is not a class or namespace name
'Alliance': undeclared identifier
'AuctionHouseId': identifier not found
'AuctionHouseId': is not a class or namespace name
'Horde': undeclared identifier
'AuctionHouseId': identifier not found
'AuctionHouseId': is not a class or namespace name
'Alliance': undeclared identifier
'AuctionHouseId': identifier not found
'AuctionHouseId': is not a class or namespace name
'Horde': undeclared identifier
'AuctionHouseId': identifier not found
'AuctionHouseId': is not a class or namespace name
'Alliance': undeclared identifier
'AuctionHouseId': identifier not found
'AuctionHouseId': is not a class or namespace name
'Horde': undeclared identifier

### Expected Behaviour

build successfully

### Steps to reproduce the problem

  +- worldserver
  |   +- mod-ah-bot
  |   +- mod-aoe-loot
  |   +- mod-autobalance
  |   +- mod-dynamic-loot-rates
  |   +- mod-gain-honor-guard
  |   +- mod-improved-bank
  |   +- mod-individual-progression
  |   +- mod-junk-to-gold
  |   +- mod-playerbots

### AC rev. hash/commit

n/a

### Operating system

Windows 11

**Comment by lotjib** [comment]
me too +

**Comment by lotjib** [comment]
> ### Current Behaviour
> Visual Studio Build Error 'GetAuctionHouseEntryFromFactionTemplate': is not a member of 'AuctionHouseMgr' 'AuctionHouseId': identifier not found 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Alliance': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Horde': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Alliance': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Horde': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Alliance': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Horde': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Alliance': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Horde': undeclared identifier
> 
> ### Expected Behaviour
> build successfully
> 
> ### Steps to reproduce the problem
> +- worldserver | +- mod-ah-bot | +- mod-aoe-loot | +- mod-autobalance | +- mod-dynamic-loot-rates | +- mod-gain-honor-guard | +- mod-improved-bank | +- mod-individual-progression | +- mod-junk-to-gold | +- mod-playerbots
> 
> ### Extra Notes
> _No response_
> 
> ### AC rev. hash/commit
> n/a
> 
> ### Operating system
> Windows 11
> 
> ### Custom changes or Modules
> _No response_

Revert this Commit b4e1653 and build - this fix problem.

**Comment by lotjib** [comment]
> ### Current Behaviour
> Visual Studio Build Error 'GetAuctionHouseEntryFromFactionTemplate': is not a member of 'AuctionHouseMgr' 'AuctionHouseId': identifier not found 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Alliance': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Horde': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Alliance': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Horde': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Alliance': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Horde': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Alliance': undeclared identifier 'AuctionHouseId': identifier not found 'AuctionHouseId': is not a class or namespace name 'Horde': undeclared identifier
> 
> ### Expected Behaviour
> build successfully
> 
> ### Steps to reproduce the problem
> +- worldserver | +- mod-ah-bot | +- mod-aoe-loot | +- mod-autobalance | +- mod-dynamic-loot-rates | +- mod-gain-honor-guard | +- mod-improved-bank | +- mod-individual-progression | +- mod-junk-to-gold | +- mod-playerbots
> 
> ### Extra Notes
> _No response_
> 
> ### AC rev. hash/commit
> n/a
> 
> ### Operating system
> Windows 11
> 
> ### Custom changes or Modules
> _No response_

git pull azerothcore

**Comment by Helias** [comment]
update your core, if you did, please put the version under `AC rev. hash/commit`
